var form = document.getElementById('resume-form');
var resumeContainer = document.getElementById('resume');
var nameDisplay = document.getElementById('name-display');
var emailDisplay = document.getElementById('email-display');
var educationDisplay = document.getElementById('education-display');
var educationContent = document.getElementById('education-content');
var workExperienceDisplay = document.getElementById('work-experience-display');
var workExperienceContent = document.getElementById('work-experience-content');
var skillsDisplay = document.getElementById('skills-display');
var skillsContent = document.getElementById('skills-content');
var editButton = document.getElementById('edit-resume');
var editFields = document.getElementById('edit-fields');
var saveEditsButton = document.getElementById('save-edits');
form.addEventListener('submit', function (e) {
    e.preventDefault();
    var name = document.getElementById('name').value;
    var email = document.getElementById('email').value;
    var education = document.getElementById('education').value;
    var workExperience = document.getElementById('work-experience').value;
    var skills = document.getElementById('skills').value;
    nameDisplay.textContent = name;
    emailDisplay.textContent = email;
    educationContent.textContent = education;
    workExperienceContent.textContent = workExperience;
    skillsContent.textContent = skills;
    editButton.style.display = 'block';
});
editButton.addEventListener('click', function () {
    editFields.style.display = 'block';
    editButton.style.display = 'none';
    var editName = document.getElementById('edit-name');
    var editEmail = document.getElementById('edit-email');
    var editEducation = document.getElementById('edit-education');
    var editWorkExperience = document.getElementById('edit-work-experience');
    var editSkills = document.getElementById('edit-skills');
    editName.value = nameDisplay.textContent || '';
    editEmail.value = emailDisplay.textContent || '';
    editEducation.value = educationContent.textContent || '';
    editWorkExperience.value = workExperienceContent.textContent || '';
    editSkills.value = skillsContent.textContent || '';
});
saveEditsButton.addEventListener('click', function () {
    var editName = document.getElementById('edit-name').value;
    var editEmail = document.getElementById('edit-email').value;
    var editEducation = document.getElementById('edit-education').value;
    var editWorkExperience = document.getElementById('edit-work-experience').value;
    var editSkills = document.getElementById('edit-skills').value;
    nameDisplay.textContent = editName;
    emailDisplay.textContent = editEmail;
    educationContent.textContent = editEducation;
    workExperienceContent.textContent = editWorkExperience;
    skillsContent.textContent = editSkills;
    editFields.style.display = 'none';
    editButton.style.display = 'block';
});
